import { Roboto } from "next/font/google";
import "./reset.css"
import "./globals.css";
import Link from "next/link";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});


export const metadata = {
  title: "SAG HARBOR",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <div className='Header'>
          <div className='HeaderTitle'>
            <Link href='/'>SAG HARBOR</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
